// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lbiubdloofsrfraqwpdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxiaXViZGxvb2ZzcmZyYXF3cGRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjA4MzQsImV4cCI6MjA2OTc5NjgzNH0.6baEnPRDbgjSaqydVuDwXPSlxTO1md19G1xggTre2xE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});